name: UpdateContents

on:
  workflow_dispatch: # このワークフローは手動でトリガーします

jobs:
  trigger_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
